### PR TITLE
Add event AI'nnov

### PR DESCRIPTION
**Pull request by kbeaugrand**

### CODE REVIEW

**Comment by smortex** [comment]
Merged, thanks!  FWIW, you can add commits to a branch and the PR will be automagically updated accordingly: no need to close it and open a new one :wink:

**Comment by kbeaugrand** [comment]
Hoo Yeah thx, I missed it... 

Regards

**Comment by smortex** [comment]
Ooops, I forgot to check the file name… The sorting order is impacted by this.  I renamed the file to fix this in 2410fed81578cccf8a9830aeef2f146e7ece4e08.  Waiting for the site to be rebuilt.

**Comment by smortex** [comment]
Look ways better :sweat_smile:

**Pull request merged**
